=== CrisCorreaS/apuntes-html-css-xml/XML/2 Validación de documentos XML/Ejercicio 5/Tarefa5a.dtd
<!ELEMENT edificio (enderezo, dataConstrucion, material?)>
    <!ELEMENT enderezo (rua, numero, poboacion, provincia, codigoPostal)>
    <!ELEMENT rua (#PCDATA)>
    <!ELEMENT numero (#PCDATA)>
    <!ELEMENT poboacion (#PCDATA)>
    <!ELEMENT provincia (#PCDATA)>
    <!ELEMENT codigoPostal (#PCDATA)>
    <!ELEMENT dataConstrucion EMPTY>
    <!ATTLIST dataConstrucion
          mes CDATA #REQUIRED
          ano CDATA #REQUIRED>
    <!ELEMENT material (#PCDATA)>
    <!ATTLIST edificio
          valor CDATA #IMPLIED
          alquiler (verdadeiro|falso) #REQUIRED>

=== CrisCorreaS/apuntes-html-css-xml/Lenguaje de Marcas/XML/2 Validación de documentos XML/Ejercicio 5/07Correa_Segade_Cristina5aXML.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE edificio SYSTEM "Tarefa5a.dtd">
<edificio alquiler="verdadeiro">
    <enderezo>
        <rua>Ponzano</rua>
        <numero>66</numero>
        <poboacion>Madrid</poboacion>
        <provincia>Madrid</provincia>
        <codigoPostal>28003</codigoPostal>
    </enderezo>
    <dataConstrucion mes="Febreiro" ano="1989"/>
    <material>Formig√≥n</material>
</edificio>
